{
  home-manager,
  nix-rosetta-builder,
  nixvim,
  ...
}:
{
  imports = [
    home-manager.darwinModules.home-manager
    nix-rosetta-builder.darwinModules.default
    nixvim.nixDarwinModules.nixvim
    ./chad
    ./documentation.nix
    ./environment.nix
    ./fonts.nix
    ./home-manager/default.nix
    ./nix/default.nix
    ./nixpkgs.nix
    ./programs
    ./services/default.nix
    ./system
  ];
}
