{
  home-manager,
  nix-rosetta-builder,
  nixvim,
  ...
}:
{
  imports = [
    {
      _module.check = true;
    }
    home-manager.darwinModules.home-manager
    nix-rosetta-builder.darwinModules.default
    nixvim.nixDarwinModules.nixvim
    ./chad
    ./documentation.nix
    ./environment.nix
    ./fonts.nix
    ./home-manager/default.nix
    ./nix/default.nix
    ./nixpkgs.nix
    ./power.nix
    ./programs
    ./nix-rosetta-builder.nix
    ./security.nix
    ./services/default.nix
    ./system
  ];
}
