{
  home-manager,
  nixvim,
  ...
}:
{
  imports = [
    home-manager.darwinModules.home-manager
    nixvim.nixDarwinModules.nixvim
    ./chad/default.nix
    ./documentation.nix
    ./environment.nix
    ./fonts.nix
    ./home-manager/default.nix
    ./nix/default.nix
    ./nixpkgs.nix
    ./programs
    ./services/default.nix
    ./system.nix
  ];
}
