{
  imports = [
    ./arrow.nix
    ./barbar.nix
    ./cmp/default.nix
    ./comment.nix
    ./conform-nvim.nix
    ./flash.nix
    ./friendly-snippets.nix
    ./fugitive.nix
    ./guess-indent.nix
    ./lint.nix
    ./lsp.nix
    ./lspkind.nix
    ./lualine.nix
    ./luasnip.nix
    ./telescope.nix
    ./treesitter.nix
    ./treesitter-context.nix
    ./treesitter-refactor.nix
    ./treesitter-textobjects
    ./web-devicons.nix
    ./which-key.nix
  ];
}
