[book]
authors = ["mstream"]
language = "en"
multilingual = false
src = "src"
title = "PureScript JSON Schema"

[build]
build-dir = "book"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
warning-policy = "error"
