{
  imports = [
    ./arrow.nix
    ./barbar.nix
    ./cmp/default.nix
    ./codecompanion.nix
    ./comment.nix
    ./conform-nvim
    ./flash.nix
    ./friendly-snippets.nix
    ./fugitive.nix
    ./gitsigns.nix
    ./guess-indent.nix
    ./lint.nix
    ./lsp.nix
    ./lsp-format.nix
    ./lsp-status.nix
    ./lspkind.nix
    ./lspsaga.nix
    ./lualine
    ./luasnip.nix
    ./neoscroll.nix
    ./none-ls.nix
    ./nvim-lightbulb.nix
    ./telescope
    ./treesitter.nix
    ./treesitter-context.nix
    ./treesitter-refactor.nix
    ./treesitter-textobjects
    ./trouble.nix
    ./web-devicons.nix
    ./which-key.nix
  ];
}
